name: App Workflow

on: [push, pull_request, workflow_dispatch]

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/workflow-template.yml
    with:
      node-version: '14'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  show-metadata:
    uses sirivo/first-project/.github/workflows/metadata.yml@mmain

